#pragma once

#include "../rendering/render_system.h"
#include "../math/rect.h"
#include "../search/result_set.h"

namespace playstate
{
	struct GuiGeometryData
	{
		Vector2 Position;
		Vector2 TexCoord;
		uint32 PaletteIndex;
	};

	static const VertexDeclaration GuiGeometryDataVertexDeclaration = {
		{ 
			{ 0, sizeof(Vector2), 2, GL_FLOAT, false },
			{ 1, sizeof(Vector2), 2, GL_FLOAT, false },
			{ 2, sizeof(uint32), 1, GL_UNSIGNED_INT, false }, 
			0 
		}
	};
	static VertexDeclarationArrayObjectFactory GuiGeometryDataVAOFactory(GuiGeometryDataVertexDeclaration);

	//
	// The geometry builder is used to append geometry generated by the user interface.
	class GuiGeometryBuilder : public ResultSet<GuiGeometryData>
	{
	public:
		GuiGeometryBuilder(RenderSystem& renderSystem);
		~GuiGeometryBuilder();

		void AddQuad(const Vector2& position, const Vector2& size);
		void AddQuad(const Vector2& position, const Vector2& size, uint32 paletteIndex);

		//
		// @return The build vertex buffer
		VertexBuffer* GetVertexBuffer();

	private:
		RenderSystem& mRenderSystem;
		VertexBuffer* mVertexBuffer;
		GuiGeometryData* mData;
	};

}
