#pragma once
#include <gl/glew.h>

#include "../types.h"
#include "../resources/resource.h"
#include "../uuid.h"

namespace playstate
{
	class TextureFormat
	{
	public:
		enum Enum {
			R,
			RGB, 
			RGBA,
			RGBA8,
			RGBA12,
			RGBA16,
			RGB10_A2,
			RGBA16F,
			DEPTH24,
			DEPTH24_STENCIL8,
		};
	};
	
	//
	// Base class for textures located on the graphics card memory.
	class Texture : public ResourceObject
	{
	protected:
		//
		// Constructor
		Texture(GLuint id, TextureFormat::Enum format);
		
	public:
		virtual ~Texture();
		
		//
		// @return This textures bit format.
		inline TextureFormat::Enum GetFormat() const {
			return mFormat;
		}

		//
		// @return A unique identifier with for this texture. This is needed because the
		//	ID object ID's generated by OpenGL are reused between deletes. The same thing is done by the
		//	operating system as well (regarding memory allocations and deletions).
		inline uint32 GetUUID() const {
			return mUUID;
		}

		inline GLuint GetID() const {
			return mTextureID;
		}

	protected:
		GLuint mTextureID;
		uint32 mUUID;
		TextureFormat::Enum mFormat;
	};

}
