#pragma once
#include <gl/glew.h>

#include "../types.h"
#include "../resources/resource.h"
#include "../uuid.h"

namespace playstate
{
	class TextureFormat
	{
	public:
		enum Enum {
			RGB, 
			RGBA,
			RGBA8,
			RGBA12,
			RGBA16,
			RGB10_A2,
			RGBA16F,
			DEPTH24,
			DEPTH24_STENCIL8,
		};
	};

	//
	// Base class for textures located on the graphics card memory.
	class Texture : public ResourceObject
	{
	protected:
		//
		// Constructor
		Texture(TextureFormat::Enum format);
		
		//
		// Binds this texture to the supplied active texture area
		//
		// @param activeTexture The texture index where we want this texture to be bound.
		// @param type The type of texture this is, for example: GL_TEXTURE_2D
		void BindToActiveTexture(uint32 activeTexture, GLenum type);

	public:
		virtual ~Texture();
		
		//
		// @return This textures bit format.
		TextureFormat::Enum GetFormat() const;

		//
		// @return A unique identifier with for this texture. This is needed because the
		//	ID object ID's generated by OpenGL are reused between deletes. The same thing is done by the
		//	operating system as well (regarding memory allocations and deletions).
		uint32 GetUUID() const;

	protected:
		GLuint mTextureId;
		uint32 mUUID;
		TextureFormat::Enum mFormat;
	};

}
